export { default as Login } from "./login";
export { default as Home } from "./home";
export { default as HistoryConsume } from "./history-consume";
export { default as StoreAdd } from "./store-add";
export { default as SubAdmin} from './sub-admin';
export { default as BusinessHours } from "./business-hours";
export { default as DeviceManage } from "./device-manage";
export { default as Timetable } from "./timetable";
export {default as StoreAuth} from './store-auth';
export {default as Map} from './map';
export {default as BindBank} from './bind-bank';
export {default as Introduce} from './introduce';
export {default as ImgStore} from './img-store';